---
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
version: 2
updates:
  - package-ecosystem: "docker"
    directories:
      - "**/*"
    schedule:
      interval: "daily"
      time: "06:00"
      timezone: "Europe/Berlin"
    commit-message:
      prefix: "chore(docker): "

  - package-ecosystem: "github-actions"
    directories:
      - "**/*"
    schedule:
      interval: "daily"
      time: "06:00"
      timezone: "Europe/Berlin"
    commit-message:
      prefix: "chore(actions): "

  - package-ecosystem: "pip"
    directories:
      - "**/*"
    schedule:
      interval: "daily"
      time: "06:00"
      timezone: "Europe/Berlin"
    commit-message:
      prefix: "chore(test): "

  - package-ecosystem: "gomod"
    directories:
      - "**/*"
    schedule:
      interval: "daily"
      time: "06:00"
      timezone: "Europe/Berlin"
    commit-message:
      prefix: "chore(go): "
