name: 'build-image'
description: 'Build the image in this repository'
inputs:
  image:
    description: 'The image tag to be used for the build'
    required: false
    default: 'tungbeier/gcloud-pubsub-emulator:test'
runs:
  using: "composite"
  steps:
    - uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3.12.0

    - uses: docker/build-push-action@10e90e3645eae34f1e60eeb005ba3a3d33f178e8 # v6.19.2
      with:
        context: .
        load: true
        tags: ${{ inputs.image }}
